---
  - name: docker, docker-compose install
    hosts: '{{ host }}'
    become: true

    vars:
      pip_install_packages:
        - name: docker
        - name: docker-compose
        - name: setuptools
      docker_install_compose: true
      docker_compose_version: "v2.29.6"
      docker_compose_arch: "{{ ansible_architecture }}"
      docker_compose_path: /usr/local/bin/docker-compose
      docker_users:
        - USER-NAME

    roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - roles/firewall.tf-ufw-docker
