---
  - name: include docker install play
    ansible.builtin.import_playbook: docker-install.yml

  - name: ollama install
    become: true
    hosts: '{{ host }}'

    vars:
      nginx: "10.0.0.5"
      fqdn: "example.com"
      ollama_hostname: "openia.{{ fqdn }}"
      ollama_port: "8080"

    roles:
      - roles/ollama-docker-install
  
