---
- name: server-install
  become: true
  hosts: "{{ host }}"
  vars:
    env: "prod"
    env_color: "033[0;33m"
    timezone: "Europe/Warsaw"

  roles:
    - roles/server-install
    - role: frzk.chrony
      vars:
        chrony_service_name: chronyd
        chrony_ntp_pools: []
        chrony_ntp_servers:
          - 0.rhel.pool.ntp.org iburst maxpoll 10
          - 1.rhel.pool.ntp.org iburst maxpoll 10
          - 2.rhel.pool.ntp.org iburst maxpoll 10
          - 3.rhel.pool.ntp.org iburst maxpoll 10
        chrony_config_file: /etc/chrony.conf
        chrony_config_driftfile: /var/lib/chrony/drift
        chrony_config_logdir: /var/log/chrony
        chrony_makestep_threshold: 5
        chrony_makestep_limit: 3

- name: include sshd play
  ansible.builtin.import_playbook: sshd.yml

- name: include ufw play
  ansible.builtin.import_playbook: ufw.yml
...